# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prometheus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10prometheus.proto\x12\x10prompb_spec.test\"H\n\x06Sample\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x1c\n\x04\x65xemplars\x18\x03 \x03(\x0b\x32\x0e.prompb_spec.test.Exemplar\"8\n\x05Label\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nname_bytes\x18\x03 \x01(\x0c\"R\n\nTimeSeries\x12\'\n\x06labels\x18\x01 \x03(\x0b\x32\x17.prompb_spec.test.Label\x12\x1b\n\x04samples\x18\x02 \x03(\x0b\x32\r.prompb_spec.test.Sample\"<\n\x0cWriteRequest\x12,\n\ntimeseries\x18\x01 \x03(\x0b\x32\x18.prompb_spec.test.TimeSeries\"9\n\x08\x45xemplar\x12\'\n\x06labels\x18\x01 \x03(\x0b\x32\x17.prompb_spec.test.Labelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prometheus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLE._serialized_start=38
  _SAMPLE._serialized_end=110
  _LABEL._serialized_start=112
  _LABEL._serialized_end=168
  _TIMESERIES._serialized_start=170
  _TIMESERIES._serialized_end=252
  _WRITEREQUEST._serialized_start=254
  _WRITEREQUEST._serialized_end=314
  _EXEMPLAR._serialized_start=316
  _EXEMPLAR._serialized_end=373
# @@protoc_insertion_point(module_scope)
